---
- name: DevOps Pipeline Setup
  hosts: localhost
  become: yes

  tasks:
    - name: Remove cdrom entries from sources.list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb cdrom:'
        state: absent

    - name: Ensure processed_logs directory exists
      ansible.builtin.file:
        path: "{{ lookup('env','PWD') }}/processed_logs"
        state: directory
        mode: '0755'

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - git
          - maven
          - docker.io
          - openjdk-17-jdk
          - ansible
        state: present
        update_cache: yes
